// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvbhnlwmmlodzkmkihfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2YmhubHdtbWxvZHprbWtpaGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTE4NTEsImV4cCI6MjA1NjA4Nzg1MX0.H_ZMJw0bg4qzE8_a9LaltPbZf9n9ma8kr3bxRpbfAI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);